"""
Experiment definitions for DcTNN training.
"""

EXPERIMENTS = [
    {
        "prefix": "OASIS",
        "name": "kspace_lambda_zero_final_l1_complex_4x_seed42",
        "dataset": "oasis",
        "image_size": (256, 256),
        "encoders": ["axial", "axial", "axial"],
        "learning": "k_space",
        "norm": "none",
        "pos_emb_type": "Rope-Axial",
        "attn_type": "complex",
        "acceleration_factors": [4],
        "lambda_schedule": "constant",
        "lambda_start": 0.0,
        "lambda_end": 0.0,
        "loss_mode": "final_only",
        "final_loss_type": "l1",
        "intermediate_loss_type": "l1",
        "epochs": 200,
        "seed": 42,
    },
    {
        "prefix": "OASIS",
        "name": "kspace_lambda_zero_final_l1_complex_4x_seed43",
        "dataset": "oasis",
        "image_size": (256, 256),
        "encoders": ["axial", "axial", "axial"],
        "learning": "k_space",
        "norm": "none",
        "pos_emb_type": "Rope-Axial",
        "attn_type": "complex",
        "acceleration_factors": [4],
        "lambda_schedule": "constant",
        "lambda_start": 0.0,
        "lambda_end": 0.0,
        "loss_mode": "final_only",
        "final_loss_type": "l1",
        "intermediate_loss_type": "l1",
        "epochs": 200,
        "seed": 43,
    },
    {
        "prefix": "OASIS",
        "name": "kspace_lambda_zero_final_l1_real_valued_4x_seed42",
        "dataset": "oasis",
        "image_size": (256, 256),
        "encoders": ["axial", "axial", "axial"],
        "learning": "k_space",
        "norm": "none",
        "pos_emb_type": "Rope-Axial",
        "attn_type": "real_valued",
        "acceleration_factors": [4],
        "lambda_schedule": "constant",
        "lambda_start": 0.0,
        "lambda_end": 0.0,
        "loss_mode": "final_only",
        "final_loss_type": "l1",
        "intermediate_loss_type": "l1",
        "epochs": 200,
        "seed": 42,
    },
    {
        "prefix": "OASIS",
        "name": "kspace_lambda_zero_final_l1_real_valued_4x_seed43",
        "dataset": "oasis",
        "image_size": (256, 256),
        "encoders": ["axial", "axial", "axial"],
        "learning": "k_space",
        "norm": "none",
        "pos_emb_type": "Rope-Axial",
        "attn_type": "real_valued",
        "acceleration_factors": [4],
        "lambda_schedule": "constant",
        "lambda_start": 0.0,
        "lambda_end": 0.0,
        "loss_mode": "final_only",
        "final_loss_type": "l1",
        "intermediate_loss_type": "l1",
        "epochs": 200,
        "seed": 43,
    },
    {
        "prefix": "OASIS",
        "name": "kspace_lambda_zero_final_l1_phase_aware_4x_seed42",
        "dataset": "oasis",
        "image_size": (256, 256),
        "encoders": ["axial", "axial", "axial"],
        "learning": "k_space",
        "norm": "none",
        "pos_emb_type": "Rope-Axial",
        "attn_type": "phase_aware",
        "acceleration_factors": [4],
        "lambda_schedule": "constant",
        "lambda_start": 0.0,
        "lambda_end": 0.0,
        "loss_mode": "final_only",
        "final_loss_type": "l1",
        "intermediate_loss_type": "l1",
        "epochs": 200,
        "seed": 42,
    },
    {
        "prefix": "OASIS",
        "name": "kspace_lambda_zero_final_l1_phase_aware_4x_seed43",
        "dataset": "oasis",
        "image_size": (256, 256),
        "encoders": ["axial", "axial", "axial"],
        "learning": "k_space",
        "norm": "none",
        "pos_emb_type": "Rope-Axial",
        "attn_type": "phase_aware",
        "acceleration_factors": [4],
        "lambda_schedule": "constant",
        "lambda_start": 0.0,
        "lambda_end": 0.0,
        "loss_mode": "final_only",
        "final_loss_type": "l1",
        "intermediate_loss_type": "l1",
        "epochs": 200,
        "seed": 43,
    },
]
